image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Java version:"
      java -version
    command: |
      # Lệnh để khởi động server Minecraft của bạn, ví dụ:
      java -Xmx1024M -Xms1024M -jar server.jar nogui
